-- Rogue class spells
IWB_ROGUE_SPELL_REF = {
	["Ambush"] = {["handler"] = IWBSpellBase, ["no_rank"] = true, ["auto_target"] = true},
	["Cheap Shot"] = {["handler"] = IWBSpellBase, ["auto_target"] = true},
	["Envenom"] = {["handler"] = IWBCombopointAndBuff, ["no_rank"] = true},
	["Eviscerate"] = {["handler"] = IWBCombopoint, ["no_rank"] = true, ["auto_target"] = true},
	["Sinister Strike"] = {["handler"] = IWBSpellBase, ["no_rank"] = true, ["auto_target"] = true},
	["Slice and Dice"] = {["handler"] = IWBCombopointAndBuff, ["no_rank"] = true},
	["Expose Armor"] = {["handler"] = IWBCombopointAndDebuff, ["no_rank"] = true, ["auto_target"] = true},
	["Garrote"] = {["handler"] = IWBSpellBase, ["no_rank"] = true, ["auto_target"] = true},
	["Kidney Shot"] = {["handler"] = IWBCombopoint, ["no_rank"] = true, ["auto_target"] = true},
	["Rupture"] = {["handler"] = IWBCombopointAndDebuff, ["no_rank"] = true, ["auto_target"] = true},
	["Backstab"] = {["handler"] = IWBSpellBase, ["no_rank"] = true, ["auto_target"] = true},
	["Feint"] = {["handler"] = IWBSpellBase, ["no_rank"] = true},
	["Flourish"] = {["handler"] = IWBCombopoint, ["no_rank"] = true, ["auto_target"] = true},
	["Gouge"] = {["handler"] = IWBSpellBase, ["no_rank"] = true},
	["Kick"] = {["handler"] = IWBSpellBase, ["no_rank"] = true, ["auto_target"] = true},
	["Sprint"] = {["handler"] = IWBSpellBase, ["no_rank"] = true},
	["Sap"] = {["handler"] = IWBSpellBase, ["no_rank"] = true},
	["Stealth"] = {["handler"] = IWBBuff, ["no_rank"] = true},
	["Vanish"] = {["handler"] = IWBSpellBase, ["no_rank"] = true},
	["Ghostly Strike"] = {["handler"] = IWBSpellBase, ["auto_target"] = true},
	["Hemorrhage"] = {["handler"] = IWBSpellBase, ["auto_target"] = true},
	["Mark for Death"] = {["handler"] = IWBSpellBase, ["auto_target"] = true},
}