-- Hunter class spells
IWB_HUNTER_SPELL_REF = {
	["Aspect of the Beast"] = {["handler"] = IWBBuff},
	["Aspect of the Cheetah"] = {["handler"] = IWBBuff},
	["Aspect of the Hawk"] = {["handler"] = IWBBuff},
	["Aspect of the Monkey"] = {["handler"] = IWBBuff},
	["Aspect of the Pack"] = {["handler"] = IWBBuff},
	["Hunter's Mark"] = {["handler"] = IWBDebuff},
	["Scorpid Sting"] = {["handler"] = IWBDebuff},
	["Serpent Sting"] = {["handler"] = IWBDebuff, ["target_hp"] = true},
	["Viper Sting"] = {["handler"] = IWBDebuff},
	["Track Beasts"] = {["handler"] = IWBBuff},
	["Track Demons"] = {["handler"] = IWBBuff},
	["Track Elementals"] = {["handler"] = IWBBuff},
	["Track Giants"] = {["handler"] = IWBBuff},
	["Track Hidden"] = {["handler"] = IWBBuff},
	["Track Humanoids"] = {["handler"] = IWBBuff},
	["Track Undead"] = {["handler"] = IWBBuff},
	["Steady Shot"] = {["handler"] = IWBSteadyShot},
	["Raptor Strike"] = {["handler"] = IWBNextMelee, ["auto_target"] = true, ["need_range"] = 3},
	["Mongoose Bite"] = {["handler"] = IWBSpellBase, ["auto_target"] = true},
	["Wing Clip"] = {["handler"] = IWBSpellBase, ["auto_target"] = true},
	["Carve"] = {["handler"] = IWBSpellBase,  ["need_range"] = 3},
}