-- Warrior class spells
IWB_WARRIOR_SPELL_REF = {
	["Heroic Strike"] = {["handler"] = IWBRageNextMelee, ["no_rank"] = true, ["auto_target"] = true},
	["Battle Shout"] = {["handler"] = IWBBuff, ["no_rank"] = true},
	["Cleave"] = {["handler"] = IWBRageNextMelee, ["no_rank"] = true, ["auto_target"] = true},
	["Rend"] = {["handler"] = IWBDebuff, ["no_rank"] = true, ["auto_target"] = true, ["target_hp"] = true},
	["Sunder Armor"] = { ["handler"] = IWBDebuffStack, ["no_rank"] = true, ["auto_target"] = true, ["duration"] = 30, ["target_hp"] = true },
	["Battle Stance"] = {["handler"] = IWBStance},
	["Defensive Stance"] = {["handler"] = IWBStance},
	["Berseker Stance"] = {["handler"] = IWBStance},
	["Charge"] = {["handler"] = IWBSpellBase, ["no_rank"] = true},
	["Hamstring"] = {["handler"] = IWBDebuff, ["no_rank"] = true, ["auto_target"] = true},
	["Mocking Blow"] = {["handler"] = IWBSpellBase, ["no_rank"] = true, ["auto_target"] = true},
	["Overpower"] = {["handler"] = IWBRage, ["no_rank"] = true, ["auto_target"] = true},
	["Thunder Clap"] = {["handler"] = IWBDebuffOrSpell, ["no_rank"] = true},
	["Demoralizing Shout"] = {["handler"] = IWBDebuffOrSpell, ["no_rank"] = true},
	["Execute"] = {["handler"] = IWBRage, ["no_rank"] = true, ["auto_target"] = true},
	["Intercept"] = {["handler"] = IWBSpellBase, ["no_rank"] = true},
	["Intervene"] = {["handler"] = IWBSpellBase, ["no_rank"] = true},
	["Revenge"] = {["handler"] = IWBSpellBase, ["no_rank"] = true, ["auto_target"] = true},
	["Shield Bash"] = {["handler"] = IWBSpellBase, ["no_rank"] = true, ["auto_target"] = true},
	["Shield Block"] = {["handler"] = IWBShieldBlock, ["no_rank"] = true},
	["Mortal Strike"] = {["handler"] = IWBRage, ["no_rank"] = true, ["auto_target"] = true},
	["Bloodthirst"] = {["handler"] = IWBRage, ["no_rank"] = true, ["auto_target"] = true},
	["Shield Slam"] = {["handler"] = IWBSpellBase, ["no_rank"] = true, ["auto_target"] = true},
	["Concussion Blow"] = {["handler"] = IWBSpellBase, ["no_rank"] = true, ["auto_target"] = true},
	["Slam"] = {["handler"] = IWBRage, ["no_rank"] = true, ["auto_target"] = true},
	["Counterattack"] = {["handler"] = IWBSpellBase, ["no_rank"] = true},
	["Whirlwind"] = {["handler"] = IWBRage},
	["Pummel"] = {["handler"] = IWBSpellBase, ["auto_target"] = true},
	["Disarm"] = {["handler"] = IWBSpellBase, ["auto_target"] = true},
	["Bloodrage"] = {["handler"] = IWBRage, ["no_rank"] = true},
}